### ISSUE TITLE
NPE when creating visualizations

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/DataTaggingLibrary#207]
Stack trace from the server app.

```
info] application - File created at: public/visualizations/is-data-FAIR~7~policy-space.png
[error] a.a.OneForOneStrategy - null
java.lang.NullPointerException: null
	at edu.harvard.iq.datatags.visualizers.graphviz.GraphvizDecisionGraphClusteredVisualizer.printChart(GraphvizDecisionGraphClusteredVisualizer.java:184)
	at edu.harvard.iq.datatags.visualizers.graphviz.GraphvizDecisionGraphClusteredVisualizer.printBody(GraphvizDecisionGraphClusteredVisualizer.java:176)
	at edu.harvard.iq.datatags.visualizers.graphviz.GraphvizVisualizer.visualize(GraphvizVisualizer.java:54)
	at actors.VisualizationActor.createDecisionGraphVisualizationFile(VisualizationActor.scala:82)
	at actors.VisualizationActor$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(VisualizationActor.scala:38)
	at actors.VisualizationActor$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(VisualizationActor.scala:37)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at actors.VisualizationActor$$anonfun$receive$1.applyOrElse(VisualizationActor.scala:37)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at actors.VisualizationActor.aroundReceive(VisualizationActor.scala:29)
```

**Comment by michbarsinai** [comment]
Also, this:
```
java.lang.NullPointerException: null
        at edu.harvard.iq.datatags.visualizers.graphviz.GraphvizDecisionGraphF11Visualizer.printChart(GraphvizDecisionGraphF11Visualizer.java:257)
        at edu.harvard.iq.datatags.visualizers.graphviz.GraphvizDecisionGraphF11Visualizer.printBody(GraphvizDecisionGraphF11Visualizer.java:247)
        at edu.harvard.iq.datatags.visualizers.graphviz.GraphvizVisualizer.visualize(GraphvizVisualizer.java:54)
        at actors.VisualizationActor.createDecisionGraphVisualizationFile(VisualizationActor.scala:82)
        at actors.VisualizationActor$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(VisualizationActor.scala:38)
        at actors.VisualizationActor$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(VisualizationActor.scala:37)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at actors.VisualizationActor$$anonfun$receive$1.applyOrElse(VisualizationActor.scala:37)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at actors.VisualizationActor.aroundReceive(VisualizationActor.scala:29)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
```

From Force11 server, working on some visualization (unclear which). Both decision graph and policy space were not created.

**Comment by michbarsinai** [comment]
Seemed to have been a disk quota issue.
