### ISSUE TITLE
Error when loading a localization that has no policy-model.xml

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/DataTaggingLibrary#223]
````
answer (? for help): \loc-load en-xx
May 15, 2019 12:41:11 AM edu.harvard.iq.datatags.cli.CliRunner promptUserForAnswer
SEVERE: Error executing command: null
java.lang.NullPointerException
	at edu.harvard.iq.datatags.parser.BaseModelLoader.lambda$loadReadmes$1(BaseModelLoader.java:28)
	at java.util.Optional.ifPresent(Optional.java:159)
	at edu.harvard.iq.datatags.parser.BaseModelLoader.lambda$loadReadmes$2(BaseModelLoader.java:28)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at edu.harvard.iq.datatags.parser.BaseModelLoader.loadReadmes(BaseModelLoader.java:25)
	at edu.harvard.iq.datatags.externaltexts.LocalizationLoader.load(LocalizationLoader.java:67)
	at edu.harvard.iq.datatags.cli.commands.LoadLocalizationCommand.execute(LoadLocalizationCommand.java:32)
	at edu.harvard.iq.datatags.cli.CliRunner.promptUserForAnswer(CliRunner.java:239)
	at edu.harvard.iq.datatags.cli.CliRunner.go(CliRunner.java:166)
	at edu.harvard.iq.datatags.mains.PolicyModelCliRunner.main(PolicyModelCliRunner.java:36)
````

**Comment by michbarsinai** [comment]
Correct answer should be not reading it, and using the original model data.
