### ISSUE TITLE
Crash when performing loc-update

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/DataTaggingLibrary#232]
````
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at edu.harvard.iq.policymodels.cli.commands.UpdateLocalizationCommand.updateNodeFiles(UpdateLocalizationCommand.java:311)
	at edu.harvard.iq.policymodels.cli.commands.UpdateLocalizationCommand.lambda$execute$0(UpdateLocalizationCommand.java:80)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at edu.harvard.iq.policymodels.cli.commands.UpdateLocalizationCommand.execute(UpdateLocalizationCommand.java:65)
	at edu.harvard.iq.policymodels.cli.CliRunner.promptUserForAnswer(CliRunner.java:242)
	at edu.harvard.iq.policymodels.cli.CliRunner.go(CliRunner.java:168)
	at edu.harvard.iq.policymodels.mains.PolicyModelCliRunner.main(PolicyModelCliRunner.java:36)
Caused by: java.lang.NullPointerException
	at java.base/java.util.TreeMap.rotateRight(TreeMap.java:2240)
	at java.base/java.util.TreeMap.fixAfterInsertion(TreeMap.java:2272)
	at java.base/java.util.TreeMap.put(TreeMap.java:580)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at edu.harvard.iq.policymodels.cli.commands.UpdateLocalizationCommand$2.visitImpl(UpdateLocalizationCommand.java:275)
	at edu.harvard.iq.policymodels.model.decisiongraph.nodes.Node$VoidVisitor.visit(Node.java:50)
	at edu.harvard.iq.policymodels.model.decisiongraph.nodes.Node$VoidVisitor.visit(Node.java:40)
	at edu.harvard.iq.policymodels.model.decisiongraph.nodes.AskNode.accept(AskNode.java:35)
	at edu.harvard.iq.policymodels.cli.commands.UpdateLocalizationCommand.lambda$updateNodeFiles$12(UpdateLocalizationCommand.java:311)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
````

**Comment by michbarsinai** [comment]
Was not able to reproduce at this point.
